server:
  port: 8081
  servlet:
    context-path: /geospatial

spring:
  application:
    name: geospatial

geospatial:
  salary:
#    minimum-wage: 1302.00
    minimum-wage: 1558.00
    annual-increase-rate: 0.18
    annual-fixed-increase: 500.00




